### ISSUE TITLE
师傅有点bug啊 java.io.EOFException

### ISSUE THREAD

**Issue by pzp12** [TryHello/DogCs4.4#9]
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
	at ssl.SecureSocket.authenticate(SecureSocket.java:77)
	at aggressor.browsers.Connect.dialogAction(Connect.java:119)
	at dialog.DialogManager$2$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by TryHello** [comment]
执行了什么操作报错的。贴个图

**Comment by pzp12** [comment]
连服务端。

**Comment by TryHello** [comment]
我测试时候没问题呢，都正常的==

**Comment by pzp12** [comment]
Cs服务端4.4吗。。。

**Comment by TryHello** [comment]
服务端也用dogcs。说明里写了的。

**Comment by pzp12** [comment]
我的我的。。。。。。。
